language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
before_install:
  - npm install -g npm
script:
  - "npm run-script lint"
  - "npm test"
notifications:
  irc: "chat.freenode.net##node-irc"
